[package]
name = "cargo-release-pr-test-two"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-release-pr-test-one = { version = "2.2.0", path = "../one" }
